"""
Strings for the commands.
"""
description = "description"
taskID = "taskID"
taskName = "taskName"
dateModified = "dateModified"
dateLastTaskEvent = "dateLastTaskEvent"
frequency = "frequency"
taskStyle = "taskStyle"
everCompleted = "everCompleted"
assigned = 'assigned'
positiveFeedback = "positiveFeedback"
negativeFeedback = "negativeFeedback"
userFeedback = "userFeedback"
name = "name"
date = "date"
userID = "userID"
firstName = "firstName"
lastName = "lastName"
isOwner = "isOwner"
assignedInitials = "assignedInitials"
completedByInitials = "completedByInitials"