application: no-slack
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /tests/?
  script: main.app

- url: /app/?
  script: main.app
  login: required

- url: /house/?
  script: main.app
  login: required  

- url: /register/?
  script: app.register.app
  login: required

- url: /requests/.*
  script: app.requests.app

- url: /static
  static_dir: static

- url: /
  script: main.app
  login: required

